sudo: false
language: python
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
